accounting/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from accounting import views

urlpatterns = [
    url(r'^levels/$', views.levels_info, name='levels_info'),
    url(r'^master-levels/$', views.master_levels_info, name='master_levels_info'),
    # url(r'^moderate-game/(?P<game_slug>[\w-]+)/(?P<session_number>\d+)/$', views.game_report_moderation, name='game_report_moderation'),
    # url(r'^my_xp/$', views.my_xp, name='my_xp'),
]


app_name = 'accounting'

games/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from games import views

urlpatterns = [
    url(r'^$', views.game_sessions_index, name='game_sessions_index'),
    url(r'^future/(?P<tag>.*)/$', views.game_sessions_index, name='game_sessions_index_tagged'),

    url(r'^free/$', views.players_required, name='players_required'),
    url(r'^free/(?P<tag>.*)/$', views.players_required, name='players_required_tagged'),

    url(r'^new/$', views.game_edit, name='create_game'),
    url(r'^details/(?P<slug>[\w-]+)/$', views.game_details, name='game_details'),
    url(r'^join/(?P<slug>[\w-]+)/$', views.join_game, name='join_game'),
    url(r'^leave/(?P<slug>[\w-]+)/$', views.leave_game, name='leave_game'),
    url(r'^remove_player/(?P<slug>[\w-]+)/(?P<user_pk>\d+)/$', views.remove_player, name='remove_player'),
    url(r'^confirm_player/(?P<slug>[\w-]+)/(?P<user_pk>\d+)/$', views.confirm_player, name='confirm_player'),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.game_edit, name='edit_game'),
    url(r'^report/(?P<game_slug>[\w-]+)/(?P<session_number>\d+)/$', views.game_report, name='report_game_session'),
]

app_name = 'games'

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from news import views

urlpatterns = [
    url(r'^$', views.index, name='news-index'),
    url(r'^(?P<url>.*/)$', views.news_item, name='news-item-detail'),
]

tabletop_planning/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from sitegate.toolbox import get_sitegate_urls
from filebrowser.sites import site

import accounting.urls
import games.urls
import games.views
import news.urls
import tabletop_tools.urls
import tags.urls
import users.urls
import users.views

from tabletop_planning import views as top_views


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None

    """
    from django.template import loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render({
        'request': request,
    }))


month_view = games.views.GameEventMonthView.as_view()

urlpatterns = [
    # project includes:
    path('', games.views.game_sessions_index, name='main_games_index'),
    path('games/', include(games.urls, namespace='games')),
    path('users/', include(users.urls, namespace='users')),
    path('tags/', include(tags.urls, namespace='tags')),
    path('accounting/', include(accounting.urls, namespace='accounting')),
    path('tools/', include(tabletop_tools.urls, namespace='tabletop_tools')),
    path('news/', include(news.urls)),

    # lone project urls:
    url(r'^about/$', top_views.statistics, name='about'),
    url(r'^privacy-policy/$', top_views.privacy_policy, name='privacy_policy'),
    url(r'^statistics/$', top_views.statistics, name='statistics'),
    url(r'^statistics/finance/$', top_views.finance_statistics, name='finance_statistics'),
    url(r'^statistics/visits/$', top_views.visits_statistics, name='visits_statistics'),
    url(r'^calendar/$', month_view, name="calendar_list_override"),
    url(r'^calendar/(?P<year>\d{4})/(?P<month>\d{2}|\d{1})/$', month_view, name="calendar_list_override"),
    url(r'^calendar/(?P<year>\d{4})/(?P<month>\d{2}|\d{1})/(?P<day>\d{2}|\d{1})/$', games.views.GameEventDayView.as_view()),
    url(r'^about/$', top_views.statistics, name='about'),
    url(
        r'^process-data/(?P<base64_data>.?[A-z0-9-_=]{2,2000}:[A-z0-9-_=]{2,2000}:[A-z0-9-_=]{2,2000})/$',
        top_views.signed_data_processor,
        name='signed_data_processor'
    ),

    url(r'^signin/$', users.views.signin, name='signin'),
    url(r'^signup/$', users.views.signup, name='signup'),
    url(r'^logout/$', users.views.logout, name='logout'),
    url(r'^password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_complete'),

    # third-parties
    path('admin/filebrowser/', site.urls),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^social-auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    url(r'^scribbler/', include('scribbler.urls')),
    url(r'^messages/', include('messages_extends.urls')),
    url(r'^calendar/', include('happenings.urls', namespace='calendar')),
    url(r'^tinymce/', include('tinymce.urls')),
    # url(r'^djrill/', include('djrill.urls')),
    # url(r'^comments/', include('django_comments_xtd.urls')),

] + get_sitegate_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import silk  # noqa
        urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
    except ImportError:
        pass

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^details/$', views.view_profile, name='view_my_profile'),
    url(r'^details/(?P<pk>\d+)/$', views.view_profile, name='view_profile'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
    url(r'^has-key-toggle/$', views.key_toggle, name='user_has_key_toggle'),
    url(r'^email-unsubscribe/$', views.email_unsubscribe, name='email_unsubscribe'),

    url(r'^mailjet/$', views.mailjet_hook, name='mailjet_hook'),
    url(
        r'^user-autocomplete/$',
        views.UserAutocomplete.as_view(),
        name='user-autocomplete',
    ),
    url(r'^google-drive-sync/enable/$', views.enable_google_drive, name='enable_google_drive'),
    url(r'^google-drive-sync/disable/$', views.disable_google_drive, name='disable_google_drive'),
]

app_name = 'users'

tabletop_planning/forms.py
# -*- coding: utf-8 -*-
from itertools import chain

# django:
from django import forms
from django.forms.models import BaseModelFormSet
from django.utils.translation import ugettext_lazy as _

# third-parties:
# from django_comments_xtd.forms import XtdCommentForm
from crispy_forms.bootstrap import FormActions, StrictButton
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML
# from parsley.decorators import parsleyfy


class BootstrapFormMixin(object):

    u"""Mixin to automate common bootstrap-related stylings.

    Example usage::

        class AuthenticationForm(BootstrapFormMixin, _AuthenticationForm):
            def __init__(self, *args, **kwargs):
                super(AuthenticationForm, self).__init__(*args, **kwargs)

                self._default_submit_button.content = _(u'Войти')

                self.helper.layout = Layout(
                    'username',
                    'password',
                    self._submit_action,
                )

    """

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(BootstrapFormMixin, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_class = 'container-fluid'
        self.helper.field_class = 'input-group'
        self.helper.attrs = {'data-parsley-validate': 'data-parsley-validate'}
        self.helper.help_text_inline = True

        self._default_submit_button = StrictButton(
            _(u'Сохранить'), type='submit', css_class='btn btn-primary js-save'
        )
        self._default_cancel_button = HTML(
            u'<a href="." class="btn btn-default js-cancel">%s</a>' % _(u'Отменить')
        )

        self._default_actions = FormActions(
            self._default_submit_button,
            self._default_cancel_button,
            css_class='form-actions clearfix',
        )

        self._submit_action = FormActions(
            self._default_submit_button,
            css_class='form-actions clearfix',
        )


class BootstrapModelForm(BootstrapFormMixin, forms.ModelForm):

    """Form class to be used with crispy.

    Note: form.__init__() method also supports ``request`` argument that will be popped and saved to form.request

    """

    def __init__(self, *args, **kwargs):
        super(BootstrapModelForm, self).__init__(*args, **kwargs)


class BootstrapForm(BootstrapFormMixin, forms.Form):
    """Same as ``BootstrapModelForm`` but for forms.Form."""

    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)


class BaseModelFormSetWithRequest(BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(BaseModelFormSetWithRequest, self).__init__(*args, **kwargs)
        self.form_kwargs['request'] = self.request


class ExtraFirstFormSet(BaseModelFormSetWithRequest):

    """Formset that outputs extra forms before forms of instances."""

    def __iter__(self):
        forms = chain(
            filter(lambda form: not form.instance.pk, self.forms),
            filter(lambda form: form.instance.pk, self.forms),
        )
        return iter(forms)


# @parsleyfy
# class CommentForm(BootstrapFormMixin, XtdCommentForm):

#     def __init__(self, *args, **kwargs):
#         super(CommentForm, self).__init__(*args, **kwargs)

#         for field in ('name', 'email', 'url'):
#             self.fields[field].widget = forms.HiddenInput()
#             self.fields[field].required = False

#         self.helper.form_tag = False

tabletop_planning/views.py
# -*- coding: utf-8 -*-

# python builtins:
import datetime

# django:
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core import signing
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import ugettext

try:
    from django.core.urlresolvers import reverse
except ImportError:
    from django.urls import reverse

# thirdparty:
from annoying.decorators import render_to


# project
from tabletop_planning.utils import get_statistics_for_interval, get_signed_data_processor_salt
from accounting.models import BalanceChange
from games.models import SessionVisit


def get_statistics():
    NOW = timezone.now()

    results = {}
    periods = {
        'one_month': 30,
        'ever': None,
        'one_year': 365,
        # 'three_years': 1096,
    }
    for period, num_days in periods.items():
        if num_days is None:
            start_date = end_date = None
            tag_stats_field = 'visits_count_all'
        else:
            start_date, end_date = (NOW - datetime.timedelta(days=num_days), NOW)
            if 28 <= num_days <= 31:
                tag_stats_field = 'visits_count_month'
            elif num_days in (365, 366):
                tag_stats_field = 'visits_count_year'
            else:
                tag_stats_field = None

        results['%s_stats' % period] = get_statistics_for_interval(start_date, end_date, tag_stats_field)

    return results


@render_to('tabletop_planning/statistics.html')
def statistics(request):
    return get_statistics()


def can_manage_balance(user):
    return (
        user.has_perm('accounting.add_balancechange')
        or
        user.has_perm('accounting.change_balancechange')
        or
        user.is_superuser
    )


@login_required
@user_passes_test(can_manage_balance)
@render_to('tabletop_planning/finance_statistics.html')
def finance_statistics(request):
    finance_statistics = BalanceChange.objects.filter(to_budget=True, verified=True).annotate_sum_per_date()
    return {'finance_statistics': finance_statistics}


@login_required
@user_passes_test(can_manage_balance)
@render_to('tabletop_planning/visits_statistics.html')
def visits_statistics(request):
    visits_statistics = SessionVisit.objects.filter(have_visited=True, verified=True, role=SessionVisit.ROLES.player).annotate_visits_per_date()
    return {'visits_statistics': visits_statistics}


@render_to('tabletop_planning/privacy_policy.html')
def privacy_policy(request):
    return {}


def signed_data_processor(request, base64_data):
    message = ugettext(u'Введенный путь был неправильный.')
    messanger = messages.error
    next_url = '/'
    try:
        data = signing.loads(base64_data, salt=get_signed_data_processor_salt())
    except signing.BadSignature:
        data = {}

    action, context = data.get('action'), data.get('context', {})
    if action == 'users.email_unsubscribe' and context.get('email'):
        user = get_user_model().objects.filter(email__iexact=context['email']).first()
        if user:
            message = None
            user.email_unsubscribe(request=request)
            if user == request.user:
                next_url = reverse('users:edit_profile')

    if message:
        messanger(request, message)

    return redirect(next_url)

tabletop_planning/templates/base.html
{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% load raven %}
{% load scribbler_tags %}
{% load common_tags %}
{% load google_analytics %}
{% spaceless %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  {# Use the .htaccess and remove these lines to avoid edge case issues. More info: h5bp.com/i/378 #}
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{{ PROJECT_NAME }} {% block page_title %}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{{ PROJECT_NAME }}. {% filter striptags|force_escape %}{% scribble 'about_long' 'shared' %}{% endscribble %}{% endfilter %}{% endblock %}">
  <link rel="image_src" href="{% block meta_image_src %}{% filter with_domain:request %}{% static 'img/logo/logo-big.png' %}{% endfilter %}{% endblock %}" />

  <meta property="og:description" content="{% block meta_og_description %}{% endblock %}" />
  <meta property="og:image" content="{% block meta_og_image_src %}{% filter with_domain:request %}{% static 'img/logo/logo-big.png' %}{% endfilter %}{% endblock %}" />
  <meta property="og:author" content="{% block meta_og_author %}{% endblock %}" />


  <meta name="viewport" content="width=device-width">

  {% block favicons %}
  	<link rel="icon" href="{% static 'favicon.ico' %}" sizes="16x16 32x32 48x48 64x64" type="image/vnd.microsoft.icon">
  	<link rel="apple-touch-icon" href="{% static 'apple-touch-icon-precomposed.png' %}">
  {% endblock %}

  {% block meta %}
  {% endblock %}

  {% compress js %}
    {% if GOOGLE_ANALYTICS_PROPERTY_ID %}{% google_analytics %}{% endif %}
  {% endcompress %}

  {# only use `block css `to totally override! do not use block.super as it do not work with offline compression #}
  {% block css %}
    {% compress css %}
      <link rel="stylesheet" href="{% static 'libs/bootstrap/less/bootstrap.less' %}" type="text/less" charset="utf-8">
      <link rel="stylesheet" href="{% static 'css/app.less' %}" type="text/less" charset="utf-8">
      <link rel="stylesheet" href="{% static 'scribbler/css/scribbler.css' %}" charset="utf-8">
      <link href="{% static 'qtip2/jquery.qtip.css' %}" rel="stylesheet">

      <link href="{% static 'happenings/css/calendar.css' %}" rel="stylesheet">

    {% endcompress %}
    <link rel="stylesheet" href="{% static 'libs/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css' %}" type="text/css" charset="utf-8">
  {% endblock %}


  {% block extra_css %}
    {# use compress block manualy in overriden block #}
  {% endblock %}

  <script src="{% static "js/libs/jquery-1.9.1.min.js" %}" type="text/javascript" charset="utf-8"></script>

  {% sentry_public_dsn as sentry_dsn %}
  <script src="//cdn.ravenjs.com/3.25.2/raven.min.js" crossorigin="anonymous"></script>
  {% if sentry_dsn %}
    <script>Raven.config('{{ sentry_dsn }}', {release: '{{ RAVEN_RELEASE|escapejs }}', environment: '{{ RAVEN_ENVIRONMENT|escapejs }}'}).install()</script>
  {% endif %}

  {% block extra_head %}
    {# use compress block manualy in overriden block #}
  {% endblock %}
</head>

<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  {# Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6. #}
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->

  <header>
    {% block header %}
    <!-- This code is taken from http://getbootstrap.com/examples/jumbotron/ -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">{% trans "Toggle navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
              <img class="icon" src="{% static 'img/logo/logo.svg' %}"  onerror="this.src='{% static 'img/logo/logo_40.png' %}' this.srcset='{% static 'img/logo/logo_40.png' %}, {% static 'img/logo/logo_80.png' %} 2x'; this.onerror=null;"/>
              <img class="name" alt="PlayHard" title="PlayHard" width="140px" src="{% static 'img/logo/logo-text.svg' %}"
                   onerror="this.src='{% static 'img/logo/logo-text-140.png' %}'; this.srcset='{% static 'img/logo/logo-text-140.png' %}, {% static 'img/logo/logo-text-280.png' %} 2x'; this.onerror=null;"/>
          </a>
          <span class="navbar-brand header_footer_common">
          {% scribble 'header_footer_common' 'shared' %}
            {% load static %}
            {% load i18n %}
              <!-- <a target="_blank" rel="nofollow" href="https://t.me/joinchat/SOME-LINK-HERE"><img src="{% static 'img/contacts/telegram-contact.svg' %}" title="Telegram" alt="Telegram channel, " /></a> -->
              <!-- <a target="_blank" rel="nofollow" href="https://www.facebook.com/groups/723935074343980/"><img src="{% static 'img/contacts/facebook-contact.svg' %}" title="Facebook" alt="Facebook group, " /></a> -->
              <!-- <a target="_blank" rel="nofollow" href="https://www.instagram.com/SOME-LINK-HERE/"><img src="{% static 'img/contacts/instagram-contact.svg' %}" title="Instagram" alt="Instagram, " /></a> -->
              <!-- <a target="_blank" rel="nofollow" href="https://vk.com/SOME-LINK-HERE"><img src="{% static 'img/contacts/vk-contact.svg' %}" title="vk.com" alt="vk.com group, " /></a> -->
              <!-- <a target="_blank" rel="nofollow" href="#" title="{% trans 'Телефон' %}" data-content="SOME_PHONE_HERE" data-toggle="popover" tabindex="0" role="button" data-placement="bottom" data-trigger="focus" data-container="body"><img src="{% static 'img/contacts/phone-contact.svg' %}" title="SOME_PHONE_HERE" alt="SOME_PHONE_HERE" /></a> -->
          {% endscribble %}
          </span>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'news-index' %}">{% trans "Новости" %}</a></li>
            <li><a href="{% url 'calendar:list' %}">{% trans "Календарь" %}</a></li>
            {# <li><a href="{% url 'games:game_sessions_index' %}">{% trans "Ближайшие игры" %}</a></li> #}
            <li><a href="{% url 'games:players_required' %}">{% trans "Набор игроков" %}</a></li>
            <li><a href="{% url 'accounting:levels_info' %}">{% trans "Цены" %}</a></li>

            <li><a href="{% url 'about' %}">{% blocktrans %}О {{ PROJECT_NAME }}{% endblocktrans %}</a></li>

            {% comment %}

            {% endcomment %}

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Инструменты' %} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'games:game_sessions_index' %}">{% trans "Ближайшие игры" %}</a></li>
		{#                <li><a href="{% url 'tabletop_tools:name_generator_index' %}">{% trans "Генератор имён" %}</a></li> #}
                <li><a href="{% url 'about' %}#section-stats">{% trans "Статистика" %}</a></li>
                <li><a href="{% url 'accounting:master_levels_info' %}">{% trans "Таблица опыта и вознаграждений для ведущих" %}</a></li>
                <li><a href="{% url 'accounting:levels_info' %}">{% trans "Таблица опыта и цен для игроков" %}</a></li>
              </ul>
            </li>
            {% if user.is_anonymous %}
              <li><a href="{% url 'signin' %}?next={{ next|default:request.path }}">{% trans "Войти" %}</a></li>
            {% else %}
	            <li class="dropdown">
	              <a href="{% url 'users:view_my_profile' %}" class="dropdown-toggle" data-toggle="dropdown">{{ request.user }} <span class="caret"></span></a>
	              <ul class="dropdown-menu" role="menu">
	                <li><a href="{% url 'users:view_my_profile' %}">{% trans "Мой профиль" %}</a></li>

                  {% if request.user.is_confirmed_master %}
                    <li><a href="{% url 'accounting:master_levels_info' %}">{% trans "Таблица опыта и оплаты ведущих" %}</a></li>
                    <li><a href="{% url 'games:create_game'%}" class="btn btn-success">{% trans "Создать игру" %}</a></li>
                  {% endif %}
	                <li><a href="{% url 'logout' %}?next={{ next|default:request.path }}">{% trans "Выход" %}</a></li>
	              </ul>
	            </li>
            {% endif %}
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
    {% endblock %}
  </header>

  <div class="container">

    {% include 'messages_extends/includes/alerts_bootstrap.html' %}

    <div class="content" role="main">
      {% block content %}{% endblock %}
    </div>

    <footer>
      {% block footer %}
      <div class="container">
        <hr>
        <div class="header_footer_common">{% scribble 'header_footer_common' 'shared' %}{% endscribble %}</div>
        {% scribble 'about_short' 'shared' %}
          <p>Сайт разработан @imposeren и возможно другими <a href="https://bitbucket.org/imposeren/tabletop-planning/commits/all">участниками</a>. Код данного сайта является открытым проектом и доступен на <a href="https://bitbucket.org/imposeren/tabletop-planning">BitBucket</a></p>
          <p>&copy; {{ PROJECT_NAME }} 2014-2019</p>
        {% endscribble %}
      </div>
      {% endblock footer %}
    </footer>
  </div>

  {# JavaScript at the bottom for fast page loading #}

  {# only use `block js `to totally override! do not use block.super as it do not work with offline compression #}
  {% block js %}
    {% compress js %}

      <script src="{% static 'libs/bootstrap/js/transition.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'libs/bootstrap/js/alert.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'libs/bootstrap/js/collapse.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'libs/bootstrap/js/tooltip.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'libs/bootstrap/js/popover.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'libs/bootstrap/js/dropdown.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'parsley/js/parsley.js' %}" ></script>
      <script src="{% static 'qtip2/jquery.qtip.js' %}" ></script>
    {% endcompress %}

    {% compress js  %}
      <script src="{% static 'js/main.js' %}" type="text/javascript" charset="utf-8"></script>
      <script src="{% static 'js/calendar.js' %}"></script>
      <script src="{% static 'js/close-alerts.js' %}"></script>

    {% endcompress %}
  {% endblock js %}

  {% block extra_js %}{% endblock %}


  {% block js_nocompress %}
    <script src="{% static 'scribbler/js/scribbler-min.js' %}"></script>
    <script src="{% static 'js/libs/holder.min.js' %}" type="text/javascript" charset="utf-8"></script>
  {% endblock %}

{% endblock %}
</body>
</html>
{% endspaceless %}