news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from news import views

urlpatterns = [
    url(r'^$', views.index, name='news-index'),
    url(r'^(?P<url>.*/)$', views.news_item, name='news-item-detail'),
]

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^details/$', views.view_profile, name='view_my_profile'),
    url(r'^details/(?P<pk>\d+)/$', views.view_profile, name='view_profile'),
    url(r'^edit/$', views.edit_profile, name='edit_profile'),
    url(r'^has-key-toggle/$', views.key_toggle, name='user_has_key_toggle'),
    url(r'^email-unsubscribe/$', views.email_unsubscribe, name='email_unsubscribe'),

    url(r'^mailjet/$', views.mailjet_hook, name='mailjet_hook'),
    url(
        r'^user-autocomplete/$',
        views.UserAutocomplete.as_view(),
        name='user-autocomplete',
    ),
    url(r'^google-drive-sync/enable/$', views.enable_google_drive, name='enable_google_drive'),
    url(r'^google-drive-sync/disable/$', views.disable_google_drive, name='disable_google_drive'),
]

app_name = 'users'

users/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

# django:
from django import forms
# from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm as _UserChangeForm
from django.contrib.auth.forms import UserCreationForm as _UserCreationForm
try:
    from django.core.urlresolvers import reverse
except ImportError:
    from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

# thirdparties:
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Layout, Field
from dal import autocomplete
from parsley.decorators import parsleyfy
# from sitegate.models import EmailConfirmation
from sitegate.signup_flows.modern import ModernSignup, ModernSignupForm

# project
from tabletop_planning.forms import BootstrapModelForm, BootstrapForm
# from tabletop_planning.utils import mail_send
from tabletop_planning.widgets import ImageWidget


User = get_user_model()


class TelegramCleanMixin(object):
    def clean_telegram_username(self):
        ignored_prefixes = ('@', 'https://t.me/')
        telegram_username = self.cleaned_data['telegram_username']
        for prefix in ignored_prefixes:
            if telegram_username.startswith(prefix):
                telegram_username = telegram_username.replace(prefix, '', 1)
                break
        return telegram_username or None


class UserAutocompleteForm(forms.Form):
    user = forms.ModelChoiceField(
        queryset=User.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='users:user-autocomplete',
            attrs={
                # Set some placeholder
                'data-placeholder': _(u'Имя или почта игрока'),
                # Only trigger autocompletion after 3 characters have been typed
                'data-minimum-input-length': 3,
            },
        )
    )


# override contrib's form to not require username (used in admin):
class UserCreationForm(TelegramCleanMixin, _UserCreationForm):

    class Meta:  # noqa: D101
        model = User
        fields = ("email", "first_name", )

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields.pop('username', '')

    def clean_email(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        email = self.cleaned_data["email"]
        try:
            User._default_manager.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )


# override contrib's form to not require username (used in admin):
class UserChangeForm(TelegramCleanMixin, _UserChangeForm):

    class Meta:  # noqa: D101
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.fields.pop('username', '')


class CustomizedSignupForm(ModernSignupForm):

    class Meta:  # noqa: D101
        model = User
        fields = ('email', 'first_name', 'password1',)


class CustomizedSignup(ModernSignup):

    form = CustomizedSignupForm


signin_layout = Layout(
    Field('username', autofocus='autofocus'),
    'password',
    'signin_flow',
    FormActions(
        Submit(
            'submit', _(u'Вход'), css_class='btn btn-primary js-signin'
        )
    )
)


signup_layout = Layout(
    Field('first_name', autofocus='autofocus'),
    'email',
    'password1',
    'signup_flow',
    FormActions(
        Submit(
            'submit', _(u'Регистрация'), css_class='btn btn-primary js-signin'
        )
    )
)


@parsleyfy
class UserEditForm(TelegramCleanMixin, BootstrapModelForm):

    class Meta:  # noqa: D101
        model = User
        fields = (
            'first_name', 'last_name', 'image', 'receive_notifications',
            'public_contacts', 'telegram_username'
            # 'email',
        )

        widgets = {
            'image': ImageWidget(),
        }

        help_texts = {
            'email': _('Имейл будет изменен не сразу: на новый адрес к вам придёт письмо содержащее ссылку для подтверждения смены имейла.'),
        }

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            # 'email', 'receive_notifications', 'first_name', 'last_name', 'image',
            'receive_notifications', 'public_contacts', 'telegram_username', 'first_name', 'last_name', 'image',
            self._default_actions
        )

    # def clean_email(self):
    #     value = self.cleaned_data.get('email')
    #     if User.objects.filter(email__iexact=value).exclude(pk=self.instance.pk).exists():
    #         raise forms.ValidationError(_('Уже существует другой пользователь с таким email адресом'))
    #     return value

    # def clean(self):
    #     super(UserEditForm, self).clean()
    #     cd = self.cleaned_data
    #     if not self.errors:
    #         if cd['email'] != self.instance.email:
    #             new_email = cd['email']
    #             # do not change email. Send confirmation email instead
    #             cd['email'] = self.instance.email

    #             url = EmailConfirmation.start_email_change(self.instance, new_email=new_email, send_email=False, next_step='finish_email_change')
    #             email_confirmation_url = self.request.build_absolute_uri(url)

    #             recipients = [new_email]

    #             mail_send(
    #                 recipients, template='email-change-confirmation',
    #                 context={'user': self.instance, 'email_confirmation_url': email_confirmation_url, 'new_email': new_email},
    #                 tags=['notification', ],
    #             )
    #             messages.info(self.request, _('Что бы подтвердить смену имейла перейдите по ссылке которая была выслана на адрес %s') % new_email)

    #     return cd


@parsleyfy
class EmailRequiredForm(BootstrapForm):

    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.helper.layout = Layout(
            'email',
            self._default_actions
        )
        self.helper.action = reverse(
            'social:complete',
            kwargs={'backend': self.request.session.get('partial_pipeline').get('backend')}
        )
        self.helper.method = 'POST'

    def clean_email(self):
        value = self.cleaned_data.get('email')
        if User.objects.filter(email__iexact=value).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError(_('Уже существует другой пользователь с таким email адресом'))
        return value

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# python builtins:
import json

# django:
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


# third-parties:
from annoying.decorators import render_to, ajax_request
from dal import autocomplete
from sitegate.decorators import signup_view, signin_view

# project:
from tabletop_planning.forms import BootstrapFormMixin
from users.signals import mailjet_webhook_event

# app:
from .models import User
from .forms import signin_layout, signup_layout, CustomizedSignup, UserEditForm, EmailRequiredForm
from .signin_flow import TunedModernSignin


@render_to('users/signin.html')
@signin_view(flow=TunedModernSignin, template='users/signin/crispy_signin_form.html')
def signin(request):
    helper = BootstrapFormMixin().helper
    helper.layout = signin_layout
    redirect_url = request.POST.get('next') or request.GET.get('next')

    return {'title': _('Вход'), 'helper': helper, 'next': redirect_url}


@render_to('users/signup.html')
@signup_view(flow=CustomizedSignup, verify_email=True, template='users/signup/crispy_signup_form.html')
def signup(request):
    helper = BootstrapFormMixin().helper
    helper.layout = signup_layout
    redirect_url = request.POST.get('next') or request.GET.get('next')
    return {'title': _('Регистрация'), 'helper': helper, 'next': redirect_url}


def logout(request):
    messages.info(request, _('Вы успешно вышли из своего аккаунта'))
    logout_view = LogoutView.as_view()
    logout_view.next_page = request.POST.get('next') or request.GET.get('next') or '/'
    return logout_view(request)


@render_to('users/user_details.html')
def view_profile(request, pk=None):
    if not pk and not request.user.is_anonymous:
        viewed_user = request.user
        return redirect(viewed_user.get_absolute_url())
    else:
        viewed_user = get_object_or_404(User, pk=pk)

    return {
        'viewed_user': viewed_user,
        'has_key_manage_permission': request.user.has_perm('users.manage_keys'),
    }


@ajax_request
def key_toggle(request):
    if not request.user.has_perm('users.manage_keys'):
        return HttpResponseForbidden()
    pk = int(request.GET.get('user_pk'))
    user = get_object_or_404(User, pk=pk)
    current_state = int(request.GET.get('current_state'))
    correct = True

    if current_state == 1:
        user.has_key = False
    elif current_state == 0:
        user.has_key = True
    else:
        correct = False
    if correct:
        user.save()
    return {'new_state': user.has_key}


@login_required
@render_to('users/user_edit.html')
def edit_profile(request):
    user = request.user
    form = UserEditForm(request.POST or None, request.FILES or None, instance=user, request=request)
    if form.is_valid():
        form.save()
        return redirect('users:view_my_profile')
    return {'form': form}


@login_required
def email_unsubscribe(request):
    request.user.email_unsubscribe(request=request)
    return redirect('users:edit_profile')


def password_reset_done(request):
    messages.info(request, _('Пароль успешно восстановлен'))
    return redirect('/')


@render_to('users/require-email.html')
def require_email(request):
    form = EmailRequiredForm(request.POST or None, request.FILES or None)

    return {'form': form}


def mailjet_hook(request):
    json_data = json.loads(request.body)
    if not isinstance(json_data, list):
        json_data = [json_data]

    for event_datum in json_data:
        mailjet_webhook_event.send(
            sender=mailjet_hook,
            event_type=event_datum['event'].lower(),
            data=event_datum,
        )
    return HttpResponse('')


class UserAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not (self.request.user.is_authenticated and self.request.user.is_staff):
            return User.objects.none()

        qs = User.objects.all()

        if self.q:
            qs = qs.filter(Q(email__istartswith=self.q) | Q(first_name__istartswith=self.q) | Q(last_name__istartswith=self.q))

        return qs


@login_required
def enable_google_drive(request):
    if not request.user.save_tables_to_drive:
        request.user.save_tables_to_drive = True
        request.user.save()
    return redirect(
        '%s?drive_access=1' % reverse('social:begin', args=['google-oauth2', ])
    )


@login_required
def disable_google_drive(request):
    if request.user.save_tables_to_drive:
        request.user.save_tables_to_drive = False
        request.user.save()
    return redirect('/')

users/templates/users/require-email.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

  <h1>{% trans 'Для регистрации на сайте необходимо указать email' %}</h1>
  {{ form }}

{% endblock %}

users/templates/users/signin.html
{% extends 'base.html' %}
{% load sitegate i18n %}

{% block content %}

  {% url 'users:view_my_profile' as view_profile_url %}

  {% if not user.is_authenticated %}
  <div class="my_signin_block">
      {% sitegate_signin_form %}
  </div>

  <div>
    {% trans "Еще не участник?" %} <a href="{% url 'signup' %}">{% trans "Зарегистрируйтесь" %}</a>
  </div>

  <div>
    {% trans "Забыли пароль?" %} <a href="{% url 'password_reset' %}">{% trans "Восстановите" %}</a>
  </div>
  {% endif %}

  <div>
   {% if not user.is_authenticated %}
    <h2>{% trans "Или войдите с помощью:" %}</h2>
    <ul>
      <li><a href="{% url 'social:begin' "google-oauth2" %}?next={{ next|default:view_profile_url }}">Google</a></li>
      <li><a href="{% url 'social:begin' "disqus" %}?next={{ next|default:view_profile_url }}">Disqus</a></li>
      <li><a href="{% url 'social:begin' "facebook" %}?next={{ next|default:view_profile_url }}">Facebook</a></li>
    </ul>
   {% elif request.user.associatable_auths %}
    <h2>{% trans "Связать с аккаунтом:" %}</h2>
    <ul>
    {% for provider, provider_name in request.user.associatable_auths %}
      <li><a href="{% url 'social:begin' provider %}?next={{ next|default:view_profile_url }}">{{ provider_name }}</a></li>
    {% endfor %}
    </ul>
   {% else %}
    <h2>{% trans "Вы успешно авторизованы!" %}</h2>
   {% endif %}

  </div>



{% endblock %}ф

users/templates/users/signup.html
{% extends 'base.html' %}
{% load sitegate i18n %}

{% block content %}

  <div class="my_signup_block">
      {% sitegate_signup_form %}
  </div>

  <div>
    {% include "users/social_auth_block.html" %}
  </div>



{% endblock %}ф

users/templates/users/social_auth_block.html
{% load i18n %}
{% trans "Или войдите с помощью:" %}:
<ul>
  <li><a href="{% url 'social:begin' "google-oauth2" %}?next={{ next }}">Google</a></li>
  <li><a href="{% url 'social:begin' "facebook" %}?next={{ next }}">Facebook</a></li>
</ul>

users/templates/users/user_details.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load compress %}
{% load common_tags %}
{% load games_tags %}

{% block extra_css %}
  {% compress css %}
    <link rel="stylesheet" href="{% static 'games/css/game-index.less' %}" type="text/less" charset="utf-8">
    <link rel="stylesheet" href="{% static 'tags/css/tags.less' %}" type="text/less" charset="utf-8">
  {% endcompress %}
{% endblock %}


{% block extra_js %}
  {% compress js %}
    <script src="{% static 'users/js/user_profile.js' %}"></script>
  {% endcompress %}
{% endblock %}


{% block page_title %}- {{ _("Люди") }} - {{ viewed_user.get_full_name }}{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-md-9 col-sm-9 col-xs-9">
      <h1>{% trans "Информация о пользователе" %}</h1>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-3">
      <div class="pull-right">
        {% include "users/blocks/key_change.html" %}
        {% if user == viewed_user %}
          <a href="{{ viewed_user.get_edit_url }}" class="btn btn-primary">{% trans "Редактировать" %}</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12 image">
      {% image_block viewed_user.image '355' %}
    </div>
    <div class="col-md-7 col-sm-7 col-xs-12">

      <h2>{{ viewed_user.get_full_name }}</h2>
      <div class="row">
        <div class="col-md-12">
        {% include 'users/blocks/has_key.html' %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">{{ viewed_user|get_field_name:"cached_total_player_experience" }}</div>
        <div class="col-md-7 col-sm-7 col-xs-12">{{ viewed_user.cached_total_player_experience }}</div>
      </div>
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">{% trans "Уровень игрока" %}</div>
        <div class="col-md-7 col-sm-7 col-xs-12">{{ viewed_user.player_level }}</div>
      </div>
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">{{ viewed_user|get_field_name:"cached_total_master_experience" }}</div>
        <div class="col-md-7 col-sm-7 col-xs-12">{{ viewed_user.cached_total_master_experience }}</div>
      </div>
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">{% trans "Уровень ведущего" %}</div>
        <div class="col-md-7 col-sm-7 col-xs-12">{{ viewed_user.master_level }}</div>
      </div>
      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">{% trans "Осталось игр по ваучеру" %}</div>
        <div class="col-md-7 col-sm-7 col-xs-12">{{ viewed_user.unused_tickets.count }}</div>
      </div>

      <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">{% trans "Цена одной игры" %}</div>
        <div class="col-md-7 col-sm-7 col-xs-12">{{ viewed_user.default_player_payment }}</div>
      </div>

      {% if viewed_user == request.user or request.user.is_staff %}
        <div class="row">
          {% if viewed_user.balance_verified >= 0 %}
            <div class="col-md-5 col-sm-5 col-xs-12">
              {% trans "Ваша добыча" %}
            </div>

            <div class="col-md-7 col-sm-7 col-xs-12">
              {{ viewed_user.balance_verified }}
            </div>
          {% else %}
            <div class="col-md-5 col-sm-5 col-xs-12">
              {% if viewed_user.is_confirmed_master %}
                {% trans "Добыча клуба" %}
              {% else %}
                {% trans "Долг за игры" %}
              {% endif %}
            </div>

            <div class="col-md-7 col-sm-7 col-xs-12">
              {{ viewed_user.debt_verified }}
              {% if viewed_user.debt_unverified != 0 %}
                {% blocktrans trimmed with debt_unverified=viewed_user.debt_unverified %}
                  (только проверенные и подтверждённые клубом отчёты; не подтверждено: {{ debt_unverified }})
                {% endblocktrans %}
              {% endif %}
            </div>
          {% endif %}
        </div>
      {% endif %}

      {% if request.user|plays_with_me:viewed_user %}
        {% for contact_info in viewed_user.all_contacts_info %}
          <div class="row">
              <div class="col-md-5 col-sm-5 col-xs-12">{{ contact_info.description }}</div>
              <div class="col-md-7 col-sm-7 col-xs-12 profile-contact-{{ contact_info.contact_field }}"><a href="{{ contact_info.link }}">{{ contact_info.display }}</a></div>
          </div>
        {% endfor %}
      {% else %}
        {% for contact_info in viewed_user.contacts_info %}
          <div class="row">
              <div class="col-md-5 col-sm-5 col-xs-12">{{ contact_info.description }}</div>
              <div class="col-md-7 col-sm-7 col-xs-12 profile-contact-{{ contact_info.contact_field }}"><a href="{{ contact_info.link }}">{{ contact_info.display }}</a></div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="row">
    {% if viewed_user == request.user and viewed_user.get_unfinished_mastering_games %}
      <h2>{% trans "Ведёте следующие игры:" %}</h2>
      <div class="game-index-full">
      {% for game in viewed_user.get_unfinished_mastering_games %}
        {% render_game_or_session game request.user image_geometry=BIGGER_GAME_IMAGE_GEOMETRY %}
      {% endfor %}
      </div>
    {% elif viewed_user.get_unfinished_active_mastering_games %}
      <h2>{% trans "Ведёт следующие игры:" %}</h2>
      <div class="game-index-full">
      {% for game in viewed_user.get_unfinished_active_mastering_games %}
        {% render_game_or_session game request.user image_geometry=BIGGER_GAME_IMAGE_GEOMETRY %}
      {% endfor %}
      </div>
    {% endif %}

    {% if viewed_user.get_playing_games %}
      <h2>{% trans "Играет в следующих играх:" %}</h2>
      <div class="game-index-full">
        {% for game in viewed_user.get_playing_games %}
          {% render_game_or_session game request.user image_geometry=BIGGER_GAME_IMAGE_GEOMETRY %}
        {% endfor %}
      </div>
    {% endif %}

    {% if viewed_user.get_played_games %}
      <h2>{% trans "Играл в следующих играх:" %}</h2>
      <div class="game-index-full">
        {% for game in viewed_user.get_played_games %}
          {% render_game_or_session game request.user image_geometry=BIGGER_GAME_IMAGE_GEOMETRY %}
        {% endfor %}
      </div>
    {% endif %}


    {% if viewed_user.get_finished_active_mastering_games %}
      <h2>{% trans "Завершенные игры:" %}</h2>
      <div class="game-index-full">
      {% for game in viewed_user.get_finished_active_mastering_games %}
        {% render_game_or_session game request.user image_geometry=BIGGER_GAME_IMAGE_GEOMETRY %}
      {% endfor %}
      </div>
    {% endif %}
  </div>

{% endblock %}

users/templates/users/user_edit.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load common_tags %}
{% load crispy_forms_tags %}
{% load compress %}

{% block extra_css %}
  {% compress css %}
    <link rel="stylesheet" href="{% static 'libs/jQuery-MultiSelect/jquery.multiselect.css' %}" rel="stylesheet">
  {% endcompress %}
{% endblock %}


{% block extra_js %}
  {% compress js %}
    <script src="{% static 'libs/jQuery-MultiSelect/jquery.multiselect.js' %}"></script>
    <script src="{% static 'users/js/user_edit.js' %}"></script>
  {% endcompress %}
{% endblock %}



{% block page_title %}- {{ _("Люди") }} - {{ request.user.get_full_name }}{% endblock %}

{% block content %}

  {% crispy form %}

  {% if request.user.is_staff %}
    <ul>
      <li><a href="{% url 'users:enable_google_drive' %}">{% trans "Сохранять таблицы опыта у меня на гугл-диске" %}</a></li>
      {% if request.user.save_tables_to_drive %}
        <li><a href="{% url 'users:disable_google_drive' %}">{% trans "*Не* сохранять таблицы опыта у меня на гугл-диске" %}</a></li>
      {% endif %}
    </ul>
  {% endif %}
  {% if request.user.associatable_auths %}
    <h2>{% trans "Связать с аккаунтом:" %}</h2>
    <ul>
    {% for provider, provider_name in request.user.associatable_auths %}
      <li><a href="{% url 'social:begin' provider %}?next={{ next|default:request.path }}">{{ provider_name }}</a></li>
    {% endfor %}
    </ul>
  {% endif %}

{% endblock %}