games/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from games import views

urlpatterns = [
    url(r'^$', views.game_sessions_index, name='game_sessions_index'),
    url(r'^future/(?P<tag>.*)/$', views.game_sessions_index, name='game_sessions_index_tagged'),

    url(r'^free/$', views.players_required, name='players_required'),
    url(r'^free/(?P<tag>.*)/$', views.players_required, name='players_required_tagged'),

    url(r'^new/$', views.game_edit, name='create_game'),
    url(r'^details/(?P<slug>[\w-]+)/$', views.game_details, name='game_details'),
    url(r'^join/(?P<slug>[\w-]+)/$', views.join_game, name='join_game'),
    url(r'^leave/(?P<slug>[\w-]+)/$', views.leave_game, name='leave_game'),
    url(r'^remove_player/(?P<slug>[\w-]+)/(?P<user_pk>\d+)/$', views.remove_player, name='remove_player'),
    url(r'^confirm_player/(?P<slug>[\w-]+)/(?P<user_pk>\d+)/$', views.confirm_player, name='confirm_player'),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.game_edit, name='edit_game'),
    url(r'^report/(?P<game_slug>[\w-]+)/(?P<session_number>\d+)/$', views.game_report, name='report_game_session'),
]

app_name = 'games'

news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from news import views

urlpatterns = [
    url(r'^$', views.index, name='news-index'),
    url(r'^(?P<url>.*/)$', views.news_item, name='news-item-detail'),
]

tabletop_planning/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from sitegate.toolbox import get_sitegate_urls
from filebrowser.sites import site

import accounting.urls
import games.urls
import games.views
import news.urls
import tabletop_tools.urls
import tags.urls
import users.urls
import users.views

from tabletop_planning import views as top_views


def handler500(request):
    """500 error handler which includes ``request`` in the context.

    Templates: `500.html`
    Context: None

    """
    from django.template import loader
    from django.http import HttpResponseServerError

    t = loader.get_template('500.html')
    return HttpResponseServerError(t.render({
        'request': request,
    }))


month_view = games.views.GameEventMonthView.as_view()

urlpatterns = [
    # project includes:
    path('', games.views.game_sessions_index, name='main_games_index'),
    path('games/', include(games.urls, namespace='games')),
    path('users/', include(users.urls, namespace='users')),
    path('tags/', include(tags.urls, namespace='tags')),
    path('accounting/', include(accounting.urls, namespace='accounting')),
    path('tools/', include(tabletop_tools.urls, namespace='tabletop_tools')),
    path('news/', include(news.urls)),

    # lone project urls:
    url(r'^about/$', top_views.statistics, name='about'),
    url(r'^privacy-policy/$', top_views.privacy_policy, name='privacy_policy'),
    url(r'^statistics/$', top_views.statistics, name='statistics'),
    url(r'^statistics/finance/$', top_views.finance_statistics, name='finance_statistics'),
    url(r'^statistics/visits/$', top_views.visits_statistics, name='visits_statistics'),
    url(r'^calendar/$', month_view, name="calendar_list_override"),
    url(r'^calendar/(?P<year>\d{4})/(?P<month>\d{2}|\d{1})/$', month_view, name="calendar_list_override"),
    url(r'^calendar/(?P<year>\d{4})/(?P<month>\d{2}|\d{1})/(?P<day>\d{2}|\d{1})/$', games.views.GameEventDayView.as_view()),
    url(r'^about/$', top_views.statistics, name='about'),
    url(
        r'^process-data/(?P<base64_data>.?[A-z0-9-_=]{2,2000}:[A-z0-9-_=]{2,2000}:[A-z0-9-_=]{2,2000})/$',
        top_views.signed_data_processor,
        name='signed_data_processor'
    ),

    url(r'^signin/$', users.views.signin, name='signin'),
    url(r'^signup/$', users.views.signup, name='signup'),
    url(r'^logout/$', users.views.logout, name='logout'),
    url(r'^password_change/$', auth_views.PasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_complete'),

    # third-parties
    path('admin/filebrowser/', site.urls),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^social-auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    url(r'^scribbler/', include('scribbler.urls')),
    url(r'^messages/', include('messages_extends.urls')),
    url(r'^calendar/', include('happenings.urls', namespace='calendar')),
    url(r'^tinymce/', include('tinymce.urls')),
    # url(r'^djrill/', include('djrill.urls')),
    # url(r'^comments/', include('django_comments_xtd.urls')),

] + get_sitegate_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import silk  # noqa
        urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
    except ImportError:
        pass

accounting/models.py
# -*- coding: utf-8 -*-

# Python builtins:
from __future__ import unicode_literals
from decimal import Decimal

# django:
from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import F, Func, Sum
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

# Third-parties:
from model_utils import FieldTracker

# project
# ...

# app:
# ...


class ExperienceReward(models.Model):
    created_datetime = models.DateTimeField(
        verbose_name=_('Дата создания'),
        default=timezone.now,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='experience_rewards',
        on_delete=models.CASCADE,
    )
    amount = models.SmallIntegerField(
        _('Количество'), default=1,
        validators=[MaxValueValidator(30000), MinValueValidator(-30000)]
    )
    comment = models.CharField(_('Коментарий'), blank=True, max_length=64)

    verified = models.BooleanField(
        _('Модерация пройдена'), default=False, db_index=True,
    )
    master_type = models.BooleanField(
        _('Опыт ведущего'), default=False,
        help_text=_('Опыт может пересчитываться в течении 2х недель и зависит от количества проведенных игр за неделю')
    )

    # not fields:
    tracker = FieldTracker()

    class Meta:  # noqa: D101
        verbose_name = _('награда опытом')
        verbose_name_plural = _('награды опытом')

    def __str__(self):
        xp_type = 'мастера' if self.master_type else 'игрока'
        return _('%(amount)s XP (%(xp_type)s)') % {'amount': self.amount, 'xp_type': xp_type}

    def save(self, *args, **kwargs):
        created = False
        if not self.pk:
            created = True

        amount_changed = self.tracker.has_changed('amount')
        verification_changed = self.tracker.has_changed('verified')

        super(ExperienceReward, self).save(*args, **kwargs)
        if created and self.verified:
            if not self.master_type:
                self.user.cached_total_player_experience += self.amount
                update_fields = ['cached_total_player_experience']
            else:
                self.user.cached_total_master_experience += self.amount
                update_fields = ['cached_total_master_experience']
            self.user.save(update_fields=update_fields)
        elif amount_changed or verification_changed:
            self.user.recalc_experience(save_on_change=True, master_type=self.master_type)

    def delete(self, *args, **kwargs):
        super(ExperienceReward, self).delete(*args, **kwargs)
        self.user.recalc_experience(save_on_change=True, master_type=self.master_type)

    def game_session(self):
        for related in ('visit_default', 'visit_bonus', 'visit_cleaned', 'visit_xp_payed',):
            visit = getattr(self, related).all().first()
            if visit:
                return visit.game_session
        return None

    game_session.short_description = _('Игровая сессия')


class BalanceChangeQS(models.QuerySet):

    def annotate_sum_per_date(self):
        return (
            self
            .annotate(created_date=Func(F('created_datetime'), function='date'))
            .order_by('created_date')
            .values('created_date')
            .annotate(
                amount_sum=Sum('amount'),
            )
        )


class BalanceChange(models.Model):

    created_datetime = models.DateTimeField(
        verbose_name=_('Дата создания'),
        default=timezone.now,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='balance_changes',
        on_delete=models.CASCADE,
    )

    to_budget = models.BooleanField(
        "В бюджет",
        default=False,
        help_text=_("Учитывать при рассчетах бюджета"),
    )

    amount = models.DecimalField(
        _('Изменение баланса'), default=1,
        max_digits=7, decimal_places=2,
        db_index=True,
    )
    comment = models.CharField(_('Коментарий'), blank=True, max_length=255)
    details = JSONField(default=None, blank=True, null=True, editable=False)

    verified = models.BooleanField(
        _('Модерация пройдена'), default=False, db_index=True,
    )

    # not fields:
    tracker = FieldTracker()
    objects = BalanceChangeQS.as_manager()

    class Meta:  # noqa: D101
        verbose_name = "BalanceChange"
        verbose_name_plural = "BalanceChanges"

    def __str__(self):
        return _('%(amount)s (%(user)s)') % {'amount': self.amount, 'user': self.user}

    @classmethod
    def build_details_from_session(cls, game_session):
        data = {
            'game_session': {
                '_model': 'games.GameSession',
                '_pk': game_session.pk,
                'number': game_session.number,
            },

            'game': {
                '_model': 'games.Game',
                '_pk': game_session.game.pk,
                'name': game_session.game.name,
            },
        }

        return data

    @classmethod
    def build_details_from_user(cls, user):
        data = {
            'user': {
                '_model': 'users.User',
                '_pk': user.pk,
                '__str__': str(user),
                'player_level': user.player_level.level,
                'master_level': user.master_level.level,
                'default_player_payment': float(user.default_player_payment),
                'default_master_payment': float(user.default_master_payment),
            },

        }
        return data

    def get_readable_details(self):
        text_details = []

        if not self.details:
            return ''

        have_visited = self.details.get('have_visited', False)
        if not have_visited:
            text_details.append("пропустил игру")

        field_name_templates = (
            ('is_free', 'посещение помечено бесплатным: {0}'),
            ('used_ticket', 'за абонемент: {0}'),
            ('used_experience', 'за опыт: {0}'),
            ('game__name', 'за игру: {0}'),
            ('game_session__number', 'за сессию: {0}'),
        )

        for field_name, template in field_name_templates:
            value = self.details.get(field_name, '')
            text = ''
            if value:
                text = template.format(value)
            else:
                if '__' in field_name:
                    key, subkey = field_name.split('__')
                    text = self.details.get(key, {}).get(subkey, '')
            if text:
                text_details.append(text)

        visitor_data = self.details.get('visitor', {})

        if visitor_data:
            field_name_templates = (
                ('user', 'посетитель: {0}'),
                ('user__master_level', 'уровень ведущего посетителя: {0}'),
                ('user__player_level', 'уровень игрока посетителя: {0}'),
                ('user__default_player_payment', 'обычная цена игр: {0}'),
                ('user__default_master_payment', 'обычная зарплата мастера: {0}'),
            )
            for field_name, template in field_name_templates:
                value = visitor_data.get(field_name, '')
                text = ''
                if value:
                    if hasattr(value, 'keys'):
                        value = value.get('__str__', '')
                    if value:
                        text = template.format(value)
                else:
                    if '__' in field_name:
                        key, subkey = field_name.split('__')
                        text = visitor_data.get(key, {}).get(subkey, '')

                if text:
                    text_details.append(text)

        return '; '.join(str(v) for v in text_details)

    get_readable_details.short_description = 'описание деталей'


class Ticket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='tickets',
        on_delete=models.CASCADE,
    )
    cost = models.DecimalField(
        _('Оригинальная стоимость'), max_digits=6, decimal_places=3,
        default=50,
        validators=[MinValueValidator(Decimal('0.01'))],
        help_text=_('Стоимость одного посещения по абонементу. ВНИМАНИЕ! изменение цены не изменит финансовую транзакцию связанную с этим билетом')
    )

    budget_balance_change = models.OneToOneField(
        BalanceChange, null=True, editable=False, related_name='budgeted_ticket',
        on_delete=models.SET_NULL,
    )
    negative_balance_change = models.OneToOneField(
        BalanceChange, null=True, editable=False, related_name='negatived_ticket',
        on_delete=models.SET_NULL,
    )

    class Meta:  # noqa: D101
        verbose_name = _('Билет на игру')
        verbose_name_plural = _('Билеты на игры')

    def __str__(self):
        return f'{self.user} ticket with cost of {self.cost}'

    def save(self, *args, **kwargs):
        super(Ticket, self).save(*args, **kwargs)
        self.update_balance()

    def update_balance(self):
        if self.cost:
            self.budget_balance_change = self.budget_balance_change or BalanceChange()
            self.negative_balance_change = self.negative_balance_change or BalanceChange()

            self.budget_balance_change.to_budget = True
            self.negative_balance_change.to_budget = False

            self.budget_balance_change.user = self.negative_balance_change.user = self.user

            self.budget_balance_change.verified = self.negative_balance_change.verified = True

            self.budget_balance_change.amount = self.cost
            self.negative_balance_change.amount = -self.cost

            self.budget_balance_change.comment = self.negative_balance_change.comment = "ticket purchase"
            self.budget_balance_change.details = self.negative_balance_change.details = {
                'ticket': {

tabletop_planning/templates/tabletop_planning/finance_statistics.html
{% extends 'base.html' %}
{% load i18n %}
{% load cache %}
{% load compress %}
{% load static %}
{% load scribbler_tags %}


{% block page_title %}- {{ _("О нас, плюс немного статистики") }}{% endblock %}

{% block meta_description %}{% trans "Финансовая статистика" %}{% endblock %}
{% block meta_og_description %}{% trans "Финансовая статистика" %}{% endblock %}

{% block extra_js %}
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    {% compress js %}
      <script src="{% static 'js/finance_statistics_page.js' %}" type="text/javascript" charset="utf-8"></script>
    {% endcompress %}

    <script type="text/javascript">
    $(document).ready(function(){
      var finance_data_dates = [];
      var finance_data_amounts = [];
      {% for finance_stat in finance_statistics %}
        finance_data_dates.push('{{ finance_stat.created_date|date:"Y-m-d" }} 12:00');
        finance_data_amounts.push({{ finance_stat.amount_sum|floatformat:"0" }})
      {% endfor %}
      graphFinanceData(finance_data_dates, finance_data_amounts);
    });

    </script>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
{% endblock %}

{% block content %}

  <h1 id="finance-stats">{% trans "Финансовая статистика" %}</h1>

  <div id="graph"></div>

{% endblock %}

tabletop_planning/templates/tabletop_planning/privacy_policy.html
{% extends 'base.html' %}
{% load i18n %}
{% load cache %}
{% load compress %}
{% load static %}
{% load scribbler_tags %}


{% block page_title %}- {{ _("Политика конфиденциальности") }}{% endblock %}

{% block meta_description %}{% trans "Политика конфиденциальности" %}{% endblock %}
{% block meta_og_description %}{% trans "Политика конфиденциальности" %}{% endblock %}


{% block content %}

  <h1 id="section-privacy_policy">{% trans "Политика конфиденциальности" %}</h1>

  {% scribble 'privacy_policy' 'shared' %}
    <p>Пользуясь сервисами Playhard, вы доверяете нам свои личные данные. Чтобы узнать, какие сведения мы сохраняем и как их используем, изучите нашу политику конфиденциальности.</p>

    <h2>Какую информацию мы собираем</h2>

    <p>По мере своих возможностей, мы стараемся собирать только ту информацию, которая необходима для работы основных функций сервиса:</p>

    <ul>
      <li>Организация и управление проведением настольных ролевых игр и других событий в клубе.</li>
      <li>Календарь событий</li>
      <li>Учет посещенных игр</li>
    </ul>

    <p>Информацию мы берем из следующих источников:</p>

    <ul>
      <li><b>Информация от пользователей.</b> Чтобы пользоваться нашими сервисами, необходимо иметь аккаунт. При его создании мы запрашиваем ваши персональные данные, например имя, адрес электронной почты, ссылки на ваши социальные профили и сохраняеи их в вашем аккаунте.
      </li>
      <li><b>Информация, которую мы получаем в результате использования вами сервисов.</b> Для обеспечения функционала логина мы сохраняем в файлах куки анонимный идентификатор, который используется для идентификации вашей текущей сессии в нашем сервисе.
      </li>
    </ul>

    <h2>Как мы используем собранные данные</h2>

    <p>Полученную информацию мы используем исключительно для предоставления основных функций сервиса. Некоторые ваши персональные данные (имя и адреса в социальных сетях) могут отображаться в вашем профиле и в событиях к которым вы присоединились.</p>

    <h2>Передача информации третьим лицам</h2>

    <p>Мы не предоставляем информацию третьим лицам.</p>

  {% endscribble %}

{% endblock %}

tabletop_planning/templates/tabletop_planning/statistics.html
{% extends 'base.html' %}
{% load i18n %}
{% load cache %}
{% load compress %}
{% load static %}
{% load scribbler_tags %}


{% block page_title %}- {{ _("О нас, плюс немного статистики") }}{% endblock %}

{% block meta_description %}{% trans "Статистика посещений" %}{% endblock %}
{% block meta_og_description %}{% trans "Статистика посещений" %}{% endblock %}

{% block extra_js %}
    {% compress js %}
      <script src="{% static 'js/statistics_page.js' %}" type="text/javascript" charset="utf-8"></script>
    {% endcompress %}

    <script type="text/javascript" src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>

{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    {% compress css %}
      <link rel="stylesheet" href="{% static 'tags/css/tags.less' %}" type="text/less" charset="utf-8">
    {% endcompress %}
{% endblock %}

{% block content %}

  <h1 id="section-about">{% trans "О нас" %}</h1>

  {% scribble 'about_long' 'shared' %}
    <p>Здравствуй, {{ request.user|default:"игрок" }}!</p>

    <p>Клуб Play Hard рад приветствовать тебя и предоставить мастера и партию на ролевую игру по вкусу.</p>

    <p>Фентези, фантастика, пост-апокалипсис и истории про зомби, игры по известным книгам и фильмам, все, что пожелает душа настоящего ролевика.</p>

    <p>Список игр в которых можно участвовать смотрите <a href="{% url 'games:players_required' %}">тут</a></p>

    <p>Также можете связаться с нами в <a href="https://vk.com/play_hard_rpg">группе vk.com</a>. Или в <a href="https://www.facebook.com/groups/723935074343980/">группе на facebook</a></p>

    <p>Наш адрес: город Киев, улица Брюллова, дом 5.</p>

    <p>Если вы уже договорились об игре, и уверены, что вас кто-то встретит в клубе, то вот как к нам пройти от станции метро "Вокзальная":</p>
    <div id="map" style="height: 30em; width:90%"></div>
  {% endscribble %}

  <h1 id="section-stats">{% trans "Статистика" %}</h1>


  {% if perms.accounting.add_balancechange or perms.accounting.change_balancechange or user.is_superuser %}
      <p><a href="{% url 'finance_statistics' %}">{% trans "Финансы" %}</a></p>
  {% endif %}

  {% if perms.accounting.add_balancechange or perms.accounting.change_balancechange or user.is_superuser %}
      <p><a href="{% url 'visits_statistics' %}">{% trans "Посещения" %}</a></p>
  {% endif %}

  {% if not ever_stats.total_sessions %}
    {% trans "В данный момент статистика еще недоступна" %}
  {% else %}
    <h2>{% trans "Проведено игровых сессий" %}</h2>
    <ul>

      <li>{% trans "За 30 дней:" %} {% include "tabletop_planning/statistics_masters_stats_block.html" with stats_data=one_month_stats %}</li>

      <li>{% trans "За год:" %} {% include "tabletop_planning/statistics_masters_stats_block.html" with stats_data=one_year_stats %}</li>

      <li>{% trans "За всё время:" %} {% include "tabletop_planning/statistics_masters_stats_block.html" with stats_data=ever_stats %}</li>

    </ul>

    <h2>{% trans "Посещений игроков" %}</h2>
    <ul>

      <li>
        {% trans "За 30 дней:" %} {% include "tabletop_planning/statistics_players_stats_block.html" with stats_data=one_month_stats %}</li>

      <li>{% trans "За год:" %} {% include "tabletop_planning/statistics_players_stats_block.html" with stats_data=one_year_stats %}</li>

      <li>{% trans "За всё время:" %} {% include "tabletop_planning/statistics_players_stats_block.html" with stats_data=ever_stats %}</li>

    </ul>

    {% if ever_stats.top_system_tags_by_visits %}
    <h2 id="popular-system-tags">{% trans "Популярные системы" %}</h2>
    <ul>

      {% if one_month_stats.top_system_tags_by_visits %}
      <li>
        {% trans "За 30-60 дней:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=one_month_stats.top_system_tags_by_visits %}
      </li>
      {% endif %}

      {% if one_year_stats.top_system_tags_by_visits %}
      <li>
        {% trans "За год:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=one_year_stats.top_system_tags_by_visits %}
      </li>
      {% endif %}

      <li>{% trans "За всё время:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=ever_stats.top_system_tags_by_visits %}
      </li>

    </ul>
    {% endif %}

    {% if ever_stats.top_setting_tags_by_visits %}
    <h2 id="popular-setting-tags">{% trans "Популярные вселенные" %}</h2>
    <ul>

      {% if one_month_stats.top_setting_tags_by_visits %}
      <li>
        {% trans "За 30-60 дней:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=one_month_stats.top_setting_tags_by_visits %}
      </li>
      {% endif %}

      {% if one_year_stats.top_setting_tags_by_visits %}
      <li>
        {% trans "За год:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=one_year_stats.top_setting_tags_by_visits %}
      </li>
      {% endif %}

      <li>{% trans "За всё время:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=ever_stats.top_setting_tags_by_visits %}
      </li>

    </ul>
    {% endif %}

    {% if ever_stats.top_other_tags_by_visits %}
    <h2 id="popular-other-tags">{% trans "Другие популярные теги" %}</h2>
    <ul>

      {% if one_month_stats.top_other_tags_by_visits %}
      <li>
        {% trans "За 30-60 дней:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=one_month_stats.top_other_tags_by_visits %}
      </li>
      {% endif %}

      {% if one_year_stats.top_other_tags_by_visits %}
      <li>
        {% trans "За год:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=one_year_stats.top_other_tags_by_visits %}
      </li>
      {% endif %}

      <li>{% trans "За всё время:" %}
        {% include "tabletop_planning/statistics_tag_ranking_block.html" with tag_ranking_data=ever_stats.top_other_tags_by_visits %}
      </li>

    </ul>
    {% endif %}

    <h2>{% trans "Загруженность клуба" %}</h2>
    <ul>
      <li>{% trans "За 30 дней:" %} {% include "tabletop_planning/statistics_week_day_stats_block.html" with stats_data=one_month_stats %}</li>
      <li>{% trans "За год:" %} {% include "tabletop_planning/statistics_week_day_stats_block.html" with stats_data=one_year_stats %}</li>
      <li>{% trans "За всё время:" %} {% include "tabletop_planning/statistics_week_day_stats_block.html" with stats_data=ever_stats %}</li>
    </ul>
  {% endif %}

{% endblock %}

tabletop_planning/templates/tabletop_planning/statistics_masters_stats_block.html
{% load i18n %}
<br/>
{% blocktrans count sessions_count=stats_data.total_sessions %}Проведена {{ sessions_count }} сессия{% plural %}Проведено {{ sessions_count }} сессий{% endblocktrans %};
<br/>
{% blocktrans with avg_players=stats_data.avg_players|floatformat:"-2" %}В среднем каждую сессию посетило {{ avg_players }} игрока{% endblocktrans %};
<br/>
{% blocktrans count masters_active_count=stats_data.masters_active_count %}{{ masters_active_count }} ведущий провел игры{% plural %}{{ masters_active_count }} ведущих провели игры{% endblocktrans %};
<br/>
{% blocktrans with sessions_per_master=stats_data.sessions_per_master|floatformat:"-2" %}В среднем каждый ведущий провёл {{ sessions_per_master }} игровых сессии{% endblocktrans %};
<br/>
{% trans "Ведущие которые провели больше всего игровых сессий:" %}
<ol>
  {% for user in stats_data.top_masters_by_sessions %}
    <li>
      <a href="{{ user.get_absolute_url }}">{{ user }}</a>:
      {% blocktrans count sessions_count=user.sessions_count %}{{ sessions_count }} проведенная сессия{% plural %}{{ sessions_count }} проведенных сессий{% endblocktrans %}
      {% blocktrans count player_visits=user.mastered_player_visits %}и {{ player_visits }} посещение игроками{% plural %}и {{ player_visits }} посещений игроками{% endblocktrans %}
    </li>
  {% endfor %}
</ol>

tabletop_planning/templates/tabletop_planning/statistics_players_stats_block.html
{% load i18n %}
{% blocktrans count player_visits=stats_data.total_player_visits %}{{ player_visits }} посещение игроками{% plural %}{{ player_visits }} посещений игроками{% endblocktrans %}
<ol>
  {% for user in stats_data.top_players_by_sessions %}
    <li>
      <a href="{{ user.get_absolute_url }}">{{ user }}</a>:
      {% blocktrans count sessions_count=user.sessions_count %}{{ sessions_count }} посещённая сессия{% plural %}{{ sessions_count }} посещенных сессий{% endblocktrans %}
    </li>
  {% endfor %}
</ol>